---
# tasks file for ansible-role-thinlinc-beta-server

- block:

  - name: Check if we already have downloaded the latest beta package
    stat:
      path: "{{ thinlinc_beta_server_bundle }}"
    register: st
    delegate_to: localhost

  - name: Download latest beta package
    get_url:
      url: "https://www.cendio.com/downloads/beta/{{ thinlinc_beta_server_bundle | basename }}"
      dest: "{{ thinlinc_beta_server_bundle }}"
      http_agent: "ansible-role-thinlinc-beta-server"
      mode: '0440'
    register: download
    delegate_to: localhost
    when: st.stat.exists == False
  
  when: thinlinc_beta_server_bundle is match("^/")
 
- name: Execute standard ansible-role-thinlinc-server
  include_role: 
    name: ansible-role-thinlinc-server
  vars:
    thinlinc_version: "{{ thinlinc_beta_version }}"
    thinlinc_build: "{{ thinlinc_beta_build }}"
    thinlinc_server_bundle: "{{ thinlinc_beta_server_bundle }}"
    thinlinc_accept_eula: "{{ thinlinc_beta_accept_eula }}"

